/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.thp.psmove;

public enum PSMove_SensorDataBasis_Type {
  SensorDataBasis_Native,
  SensorDataBasis_OpenGL;

  public final int swigValue() {
    return swigValue;
  }

  public static PSMove_SensorDataBasis_Type swigToEnum(int swigValue) {
    PSMove_SensorDataBasis_Type[] swigValues = PSMove_SensorDataBasis_Type.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (PSMove_SensorDataBasis_Type swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + PSMove_SensorDataBasis_Type.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private PSMove_SensorDataBasis_Type() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private PSMove_SensorDataBasis_Type(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private PSMove_SensorDataBasis_Type(PSMove_SensorDataBasis_Type swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

