/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.thp.psmove;

public class _PSMove_3AxisTransform {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected _PSMove_3AxisTransform(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(_PSMove_3AxisTransform obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        psmoveapiJNI.delete__PSMove_3AxisTransform(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setRow0(SWIGTYPE_p_float value) {
    psmoveapiJNI._PSMove_3AxisTransform_row0_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getRow0() {
    long cPtr = psmoveapiJNI._PSMove_3AxisTransform_row0_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setRow1(SWIGTYPE_p_float value) {
    psmoveapiJNI._PSMove_3AxisTransform_row1_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getRow1() {
    long cPtr = psmoveapiJNI._PSMove_3AxisTransform_row1_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setRow2(SWIGTYPE_p_float value) {
    psmoveapiJNI._PSMove_3AxisTransform_row2_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getRow2() {
    long cPtr = psmoveapiJNI._PSMove_3AxisTransform_row2_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public void setM(SWIGTYPE_p_float value) {
    psmoveapiJNI._PSMove_3AxisTransform_m_set(swigCPtr, this, SWIGTYPE_p_float.getCPtr(value));
  }

  public SWIGTYPE_p_float getM() {
    long cPtr = psmoveapiJNI._PSMove_3AxisTransform_m_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_float(cPtr, false);
  }

  public _PSMove_3AxisTransform() {
    this(psmoveapiJNI.new__PSMove_3AxisTransform(), true);
  }

}
