//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace io.thp.psmove {

public enum BatteryLevel {
  Batt_MIN = 0x00,
  Batt_20Percent = 0x01,
  Batt_40Percent = 0x02,
  Batt_60Percent = 0x03,
  Batt_80Percent = 0x04,
  Batt_MAX = 0x05,
  Batt_CHARGING = 0xEE,
  Batt_CHARGING_DONE = 0xEF
}

}
