/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.thp.psmove;

public enum Button {
  Btn_TRIANGLE(1 << 4),
  Btn_CIRCLE(1 << 5),
  Btn_CROSS(1 << 6),
  Btn_SQUARE(1 << 7),
  Btn_SELECT(1 << 8),
  Btn_START(1 << 11),
  Btn_PS(1 << 16),
  Btn_MOVE(1 << 19),
  Btn_T(1 << 20);

  public final int swigValue() {
    return swigValue;
  }

  public static Button swigToEnum(int swigValue) {
    Button[] swigValues = Button.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (Button swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + Button.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private Button() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private Button(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private Button(Button swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

