/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGJAVA
#define SWIGJAVA
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else



 /**
 * PS Move API - An interface for the PS Move Motion Controller
 * Copyright (c) 2011, 2012 Thomas Perl <m@thp.io>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 **/


#include "psmove.h"
#include "psmove_tracker.h"
#include "psmove_fusion.h"


SWIGINTERN PSMove *new_PSMove__SWIG_0(void){
        return psmove_connect_by_id(0);
    }
SWIGINTERN PSMove *new_PSMove__SWIG_1(int id){
        return psmove_connect_by_id(id);
    }
SWIGINTERN void PSMove_enable_orientation(PSMove *self,int enabled){
        psmove_enable_orientation(self, enabled);
    }
SWIGINTERN int PSMove_has_orientation(PSMove *self){
        return psmove_has_orientation(self);
    }
SWIGINTERN int PSMove_has_calibration(PSMove *self){
        return psmove_has_calibration(self);
    }
SWIGINTERN void PSMove_reset_orientation(PSMove *self){
        psmove_reset_orientation(self);
    }
SWIGINTERN void PSMove_set_leds(PSMove *self,int r,int g,int b){
        psmove_set_leds(self, r, g, b);
    }
SWIGINTERN void PSMove_set_rumble(PSMove *self,int rumble){
        psmove_set_rumble(self, rumble);
    }
SWIGINTERN int PSMove_update_leds(PSMove *self){
        return psmove_update_leds(self);
    }
SWIGINTERN void PSMove_set_rate_limiting(PSMove *self,int enabled){
        psmove_set_rate_limiting(self, enabled);
    }
SWIGINTERN int PSMove_pair(PSMove *self){
        return psmove_pair(self);
    }
SWIGINTERN int PSMove_pair_custom(PSMove *self,char const *btaddr){
        return psmove_pair_custom(self, btaddr);
    }
SWIGINTERN char const *PSMove_get_serial(PSMove *self){
        static char *result = NULL;
        if (result != NULL) {
            free(result);
        }
        result = psmove_get_serial(self);
        return result;
    }
SWIGINTERN int PSMove_is_remote(PSMove *self){
        return psmove_is_remote(self);
    }
SWIGINTERN int PSMove_poll(PSMove *self){
        return psmove_poll(self);
    }
SWIGINTERN int PSMove_get_buttons(PSMove *self){
        return psmove_get_buttons(self);
    }
SWIGINTERN int PSMove_get_battery(PSMove *self){
        return psmove_get_battery(self);
    }
SWIGINTERN int PSMove_get_temperature(PSMove *self){
        return psmove_get_temperature(self);
    }
SWIGINTERN float PSMove_get_temperature_in_celsius(PSMove *self){
        return psmove_get_temperature_in_celsius(self);
    }
SWIGINTERN int PSMove_get_trigger(PSMove *self){
        return psmove_get_trigger(self);
    }
SWIGINTERN void delete_PSMove(PSMove *self){
        psmove_disconnect(self);
    }


void
PSMove_get_accelerometer_frame(PSMove *move, enum PSMove_Frame frame,
    float *x, float *y, float *z) {
    psmove_get_accelerometer_frame(move, frame, x, y, z);
}

void
PSMove_get_gyroscope_frame(PSMove *move, enum PSMove_Frame frame,
    float *x, float *y, float *z) {
    psmove_get_gyroscope_frame(move, frame, x, y, z);
}

void
PSMove_get_magnetometer_vector(PSMove *move, float *x, float *y, float *z)
{
    psmove_get_magnetometer_vector(move, x, y, z);
}

void
PSMove_get_orientation(PSMove *move, float *w, float *x, float *y, float *z)
{
    psmove_get_orientation(move, w, x, y, z);
}

void
PSMove_get_button_events(PSMove *move,
    unsigned int *pressed, unsigned int *released)
{
    psmove_get_button_events(move, pressed, released);
}

int
PSMove_connection_type_get(PSMove *move) {
    return psmove_connection_type(move);
}

int
PSMove_ax_get(PSMove *move) {
    int result;
    psmove_get_accelerometer(move, &result, NULL, NULL);
    return result;
}

int
PSMove_ay_get(PSMove *move) {
    int result;
    psmove_get_accelerometer(move, NULL, &result, NULL);
    return result;
}

int
PSMove_az_get(PSMove *move) {
    int result;
    psmove_get_accelerometer(move, NULL, NULL, &result);
    return result;
}

int
PSMove_gx_get(PSMove *move) {
    int result;
    psmove_get_gyroscope(move, &result, NULL, NULL);
    return result;
}

int
PSMove_gy_get(PSMove *move) {
    int result;
    psmove_get_gyroscope(move, NULL, &result, NULL);
    return result;
}

int
PSMove_gz_get(PSMove *move) {
    int result;
    psmove_get_gyroscope(move, NULL, NULL, &result);
    return result;
}


int
PSMove_mx_get(PSMove *move) {
    int result;
    psmove_get_magnetometer(move, &result, NULL, NULL);
    return result;
}

int
PSMove_my_get(PSMove *move) {
    int result;
    psmove_get_magnetometer(move, NULL, &result, NULL);
    return result;
}

int
PSMove_mz_get(PSMove *move) {
    int result;
    psmove_get_magnetometer(move, NULL, NULL, &result);
    return result;
}

int
init(enum PSMove_Version version)
{
    return psmove_init(version);
}

void set_remote_config(enum PSMove_RemoteConfig config)
{
    return psmove_set_remote_config(config);
}

int count_connected()
{
    return psmove_count_connected();
}

void reinit()
{
    return psmove_reinit();
}

#ifdef PSMOVE_BUILD_TRACKER

int
PSMoveTrackerRGBImage_size_get(PSMoveTrackerRGBImage *image)
{
    return 3 * image->width * image->height;
}

float
PSMoveTracker_dimming_get(PSMoveTracker *tracker)
{
    return psmove_tracker_get_dimming(tracker);
}

void
PSMoveTracker_dimming_set(PSMoveTracker *tracker, float dimming)
{
    psmove_tracker_set_dimming(tracker, dimming);
}

void
PSMoveTracker_exposure_set(PSMoveTracker *tracker,
    enum PSMoveTracker_Exposure exposure)
{
    psmove_tracker_set_exposure(tracker, exposure);
}

enum PSMoveTracker_Exposure
PSMoveTracker_exposure_get(PSMoveTracker *tracker)
{
    return psmove_tracker_get_exposure(tracker);
}

void
PSMoveTracker_get_color(PSMoveTracker *tracker, PSMove *move,
    unsigned char *r, unsigned char *g, unsigned char *b)
{
    psmove_tracker_get_color(tracker, move, r, g, b);
}

void
PSMoveTracker_get_camera_color(PSMoveTracker *tracker, PSMove *move,
    unsigned char *r, unsigned char *g, unsigned char *b)
{
    psmove_tracker_get_camera_color(tracker, move, r, g, b);
}

void
PSMoveTracker_get_position(PSMoveTracker *tracker, PSMove *move,
    float *x, float *y, float *radius)
{
    psmove_tracker_get_position(tracker, move, x, y, radius);
}

void
PSMoveTracker_get_size(PSMoveTracker *tracker, int *width, int *height)
{
    return psmove_tracker_get_size(tracker, width, height);
}

void
PSMoveFusion_get_position(PSMoveFusion *fusion, PSMove *move,
            float *x, float *y, float *z)
{
    psmove_fusion_get_position(fusion, move, x, y, z);
}

#endif /* PSMOVE_BUILD_TRACKER */



#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1Ext_1Device_1Info_1dev_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PSMove_Ext_Device_Info *arg1 = (PSMove_Ext_Device_Info *) 0 ;
  unsigned short arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove_Ext_Device_Info **)&jarg1; 
  arg2 = (unsigned short)jarg2; 
  if (arg1) (arg1)->dev_id = arg2;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1Ext_1Device_1Info_1dev_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove_Ext_Device_Info *arg1 = (PSMove_Ext_Device_Info *) 0 ;
  unsigned short result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove_Ext_Device_Info **)&jarg1; 
  result = (unsigned short) ((arg1)->dev_id);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1Ext_1Device_1Info_1dev_1info_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  PSMove_Ext_Device_Info *arg1 = (PSMove_Ext_Device_Info *) 0 ;
  unsigned char *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove_Ext_Device_Info **)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  {
    size_t ii;
    unsigned char *b = (unsigned char *) arg1->dev_info;
    for (ii = 0; ii < (size_t)38; ii++) b[ii] = *((unsigned char *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1Ext_1Device_1Info_1dev_1info_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  PSMove_Ext_Device_Info *arg1 = (PSMove_Ext_Device_Info *) 0 ;
  unsigned char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove_Ext_Device_Info **)&jarg1; 
  result = (unsigned char *)(unsigned char *) ((arg1)->dev_info);
  *(unsigned char **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI_new_1PSMove_1Ext_1Device_1Info(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PSMove_Ext_Device_Info *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PSMove_Ext_Device_Info *)calloc(1, sizeof(PSMove_Ext_Device_Info));
  *(PSMove_Ext_Device_Info **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_delete_1PSMove_1Ext_1Device_1Info(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PSMove_Ext_Device_Info *arg1 = (PSMove_Ext_Device_Info *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PSMove_Ext_Device_Info **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisVector_1x_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisVector **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT jfloat JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisVector_1x_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisVector **)&jarg1; 
  result = (float) ((arg1)->x);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisVector_1y_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisVector **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT jfloat JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisVector_1y_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisVector **)&jarg1; 
  result = (float) ((arg1)->y);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisVector_1z_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloat jarg2) {
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisVector **)&jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->z = arg2;
}


SWIGEXPORT jfloat JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisVector_1z_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisVector **)&jarg1; 
  result = (float) ((arg1)->z);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisVector_1v_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisVector **)&jarg1; 
  arg2 = *(float **)&jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->v;
    for (ii = 0; ii < (size_t)3; ii++) b[ii] = *((float *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisVector_1v_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisVector **)&jarg1; 
  result = (float *)(float *) ((arg1)->v);
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI_new_1_1PSMove_13AxisVector(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct _PSMove_3AxisVector *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct _PSMove_3AxisVector *)calloc(1, sizeof(struct _PSMove_3AxisVector));
  *(struct _PSMove_3AxisVector **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_delete_1_1PSMove_13AxisVector(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct _PSMove_3AxisVector **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisTransform_1row0_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisTransform **)&jarg1; 
  arg2 = *(float **)&jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->row0;
    for (ii = 0; ii < (size_t)3; ii++) b[ii] = *((float *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisTransform_1row0_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisTransform **)&jarg1; 
  result = (float *)(float *) ((arg1)->row0);
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisTransform_1row1_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisTransform **)&jarg1; 
  arg2 = *(float **)&jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->row1;
    for (ii = 0; ii < (size_t)3; ii++) b[ii] = *((float *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisTransform_1row1_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisTransform **)&jarg1; 
  result = (float *)(float *) ((arg1)->row1);
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisTransform_1row2_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisTransform **)&jarg1; 
  arg2 = *(float **)&jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->row2;
    for (ii = 0; ii < (size_t)3; ii++) b[ii] = *((float *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisTransform_1row2_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisTransform **)&jarg1; 
  result = (float *)(float *) ((arg1)->row2);
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisTransform_1m_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisTransform **)&jarg1; 
  arg2 = *(float **)&jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->m;
    for (ii = 0; ii < (size_t)9; ii++) b[ii] = *((float *) arg2 + ii);
  }
  
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI__1PSMove_13AxisTransform_1m_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(struct _PSMove_3AxisTransform **)&jarg1; 
  result = (float *)(float *) ((arg1)->m);
  *(float **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI_new_1_1PSMove_13AxisTransform(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  struct _PSMove_3AxisTransform *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (struct _PSMove_3AxisTransform *)calloc(1, sizeof(struct _PSMove_3AxisTransform));
  *(struct _PSMove_3AxisTransform **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_delete_1_1PSMove_13AxisTransform(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(struct _PSMove_3AxisTransform **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1init(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  enum PSMove_Version arg1 ;
  enum PSMove_Bool result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (enum PSMove_Version)jarg1; 
  result = (enum PSMove_Bool)psmove_init(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1set_1remote_1config(JNIEnv *jenv, jclass jcls, jint jarg1) {
  enum PSMove_RemoteConfig arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (enum PSMove_RemoteConfig)jarg1; 
  psmove_set_remote_config(arg1);
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1count_1connected(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)psmove_count_connected();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1connect(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PSMove *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PSMove *)psmove_connect();
  *(PSMove **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1connect_1by_1id(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  PSMove *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (PSMove *)psmove_connect_by_id(arg1);
  *(PSMove **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1connection_1type(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Connection_Type result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (enum PSMove_Connection_Type)psmove_connection_type(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1is_1remote(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (enum PSMove_Bool)psmove_is_remote(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1serial(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (char *)psmove_get_serial(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1pair(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (enum PSMove_Bool)psmove_pair(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1pair_1custom(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  char *arg2 = (char *) 0 ;
  enum PSMove_Bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (enum PSMove_Bool)psmove_pair_custom(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1set_1rate_1limiting(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (enum PSMove_Bool)jarg2; 
  psmove_set_rate_limiting(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1set_1leds(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2, jshort jarg3, jshort jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned char arg2 ;
  unsigned char arg3 ;
  unsigned char arg4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  arg3 = (unsigned char)jarg3; 
  arg4 = (unsigned char)jarg4; 
  psmove_set_leds(arg1,arg2,arg3,arg4);
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1set_1led_1pwm_1frequency(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned long arg2 ;
  enum PSMove_Bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (unsigned long)jarg2; 
  result = (enum PSMove_Bool)psmove_set_led_pwm_frequency(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1set_1rumble(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jshort jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned char arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (unsigned char)jarg2; 
  psmove_set_rumble(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1update_1leds(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Update_Result result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (enum PSMove_Update_Result)psmove_update_leds(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1poll(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)psmove_poll(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1ext_1data(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_Ext_Data *arg2 = (PSMove_Ext_Data *) 0 ;
  enum PSMove_Bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(PSMove_Ext_Data **)&jarg2; 
  result = (enum PSMove_Bool)psmove_get_ext_data(arg1,(unsigned char (*)[5])arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1send_1ext_1data(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jshort jarg3) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char arg3 ;
  enum PSMove_Bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(unsigned char **)&jarg2; 
  arg3 = (unsigned char)jarg3; 
  result = (enum PSMove_Bool)psmove_send_ext_data(arg1,(unsigned char const *)arg2,arg3);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1buttons(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (unsigned int)psmove_get_buttons(arg1);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1button_1events(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3) {
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(unsigned int **)&jarg2; 
  arg3 = *(unsigned int **)&jarg3; 
  psmove_get_button_events(arg1,arg2,arg3);
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1is_1ext_1connected(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (enum PSMove_Bool)psmove_is_ext_connected(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1ext_1device_1info(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_Ext_Device_Info *arg2 = (PSMove_Ext_Device_Info *) 0 ;
  enum PSMove_Bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(PSMove_Ext_Device_Info **)&jarg2; 
  result = (enum PSMove_Bool)psmove_get_ext_device_info(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1battery(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Battery_Level result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (enum PSMove_Battery_Level)psmove_get_battery(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1temperature(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)psmove_get_temperature(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1temperature_1in_1celsius(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (float)psmove_get_temperature_in_celsius(arg1);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jshort JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1trigger(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jshort jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned char result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (unsigned char)psmove_get_trigger(arg1);
  jresult = (jshort)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1accelerometer(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int *arg4 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  arg3 = *(int **)&jarg3; 
  arg4 = *(int **)&jarg4; 
  psmove_get_accelerometer(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1gyroscope(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int *arg4 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  arg3 = *(int **)&jarg3; 
  arg4 = *(int **)&jarg4; 
  psmove_get_gyroscope(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1magnetometer(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int *arg4 = (int *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(int **)&jarg2; 
  arg3 = *(int **)&jarg3; 
  arg4 = *(int **)&jarg4; 
  psmove_get_magnetometer(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1accelerometer_1frame(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = *(float **)&jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = *(float **)&jarg5; 
  psmove_get_accelerometer_frame(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1gyroscope_1frame(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = *(float **)&jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = *(float **)&jarg5; 
  psmove_get_gyroscope_frame(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1magnetometer_1vector(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  float *arg2 = (float *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(float **)&jarg2; 
  arg3 = *(float **)&jarg3; 
  arg4 = *(float **)&jarg4; 
  psmove_get_magnetometer_vector(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1magnetometer_13axisvector(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(PSMove_3AxisVector **)&jarg2; 
  psmove_get_magnetometer_3axisvector(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1reset_1magnetometer_1calibration(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  psmove_reset_magnetometer_calibration(arg1);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1save_1magnetometer_1calibration(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  psmove_save_magnetometer_calibration(arg1);
}


SWIGEXPORT jfloat JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1magnetometer_1calibration_1range(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (float)psmove_get_magnetometer_calibration_range(arg1);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1has_1calibration(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (enum PSMove_Bool)psmove_has_calibration(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1dump_1calibration(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  psmove_dump_calibration(arg1);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1enable_1orientation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (enum PSMove_Bool)jarg2; 
  psmove_enable_orientation(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1has_1orientation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (enum PSMove_Bool)psmove_has_orientation(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1orientation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jlong jarg3, jlong jarg4, jlong jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  float *arg2 = (float *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(float **)&jarg2; 
  arg3 = *(float **)&jarg3; 
  arg4 = *(float **)&jarg4; 
  arg5 = *(float **)&jarg5; 
  psmove_get_orientation(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1reset_1orientation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  psmove_reset_orientation(arg1);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1set_1orientation_1fusion_1type(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMoveOrientation_Fusion_Type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (enum PSMoveOrientation_Fusion_Type)jarg2; 
  psmove_set_orientation_fusion_type(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1set_1calibration_1pose(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_CalibrationPose_Type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (enum PSMove_CalibrationPose_Type)jarg2; 
  psmove_set_calibration_pose(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1set_1calibration_1transform(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisTransform *arg2 = (PSMove_3AxisTransform *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(PSMove_3AxisTransform **)&jarg2; 
  psmove_set_calibration_transform(arg1,(struct _PSMove_3AxisTransform const *)arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1identity_1gravity_1calibration_1direction(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(PSMove_3AxisVector **)&jarg2; 
  psmove_get_identity_gravity_calibration_direction(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1transformed_1gravity_1calibration_1direction(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(PSMove_3AxisVector **)&jarg2; 
  psmove_get_transformed_gravity_calibration_direction(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1identity_1magnetometer_1calibration_1direction(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(PSMove_3AxisVector **)&jarg2; 
  psmove_get_identity_magnetometer_calibration_direction(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1transformed_1magnetometer_1calibration_1direction(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(PSMove_3AxisVector **)&jarg2; 
  psmove_get_transformed_magnetometer_calibration_direction(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1set_1magnetometer_1calibration_1direction(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(PSMove_3AxisVector **)&jarg2; 
  psmove_set_magnetometer_calibration_direction(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1set_1sensor_1data_1basis(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_SensorDataBasis_Type arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (enum PSMove_SensorDataBasis_Type)jarg2; 
  psmove_set_sensor_data_basis(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1set_1sensor_1data_1transform(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisTransform *arg2 = (PSMove_3AxisTransform *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(PSMove_3AxisTransform **)&jarg2; 
  psmove_set_sensor_data_transform(arg1,(struct _PSMove_3AxisTransform const *)arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1transformed_1magnetometer_1direction(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = *(PSMove_3AxisVector **)&jarg2; 
  psmove_get_transformed_magnetometer_direction(arg1,arg2);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1transformed_1accelerometer_1frame_13axisvector(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  PSMove_3AxisVector *arg3 = (PSMove_3AxisVector *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = *(PSMove_3AxisVector **)&jarg3; 
  psmove_get_transformed_accelerometer_frame_3axisvector(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1transformed_1accelerometer_1frame_1direction(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  PSMove_3AxisVector *arg3 = (PSMove_3AxisVector *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = *(PSMove_3AxisVector **)&jarg3; 
  psmove_get_transformed_accelerometer_frame_direction(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1get_1transformed_1gyroscope_1frame_13axisvector(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jlong jarg3, jobject jarg3_) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  PSMove_3AxisVector *arg3 = (PSMove_3AxisVector *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg3_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = *(PSMove_3AxisVector **)&jarg3; 
  psmove_get_transformed_gyroscope_frame_3axisvector(arg1,arg2,arg3);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1disconnect(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  psmove_disconnect(arg1);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1reinit(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  psmove_reinit();
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1util_1get_1ticks(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  long result;
  
  (void)jenv;
  (void)jcls;
  result = (long)psmove_util_get_ticks();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1util_1get_1data_1dir(JNIEnv *jenv, jclass jcls) {
  jstring jresult = 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (char *)psmove_util_get_data_dir();
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1util_1get_1file_1path(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jstring jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (char *)psmove_util_get_file_path((char const *)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1util_1get_1system_1file_1path(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jstring jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (char *)psmove_util_get_system_file_path((char const *)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1util_1get_1env_1int(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jint jresult = 0 ;
  char *arg1 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (int)psmove_util_get_env_int((char const *)arg1);
  jresult = (jint)result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_io_thp_psmove_psmoveapiJNI_psmove_1util_1get_1env_1string(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jstring jresult = 0 ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (char *)psmove_util_get_env_string((char const *)arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1connection_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_connection_type_get(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1ax_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_ax_get(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1ay_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_ay_get(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1az_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_az_get(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1gx_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_gx_get(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1gy_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_gy_get(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1gz_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_gz_get(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1mx_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_mx_get(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1my_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_my_get(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1mz_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_mz_get(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI_new_1PSMove_1_1SWIG_10(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  PSMove *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (PSMove *)new_PSMove__SWIG_0();
  *(PSMove **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_io_thp_psmove_psmoveapiJNI_new_1PSMove_1_1SWIG_11(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  PSMove *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (PSMove *)new_PSMove__SWIG_1(arg1);
  *(PSMove **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1get_1accelerometer_1frame(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jfloatArray jarg3, jfloatArray jarg4, jfloatArray jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  float temp3 ;
  float temp4 ;
  float temp5 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp3 = (float)0;
    arg3 = &temp3; 
  }
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp4 = (float)0;
    arg4 = &temp4; 
  }
  {
    if (!jarg5) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg5) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp5 = (float)0;
    arg5 = &temp5; 
  }
  PSMove_get_accelerometer_frame(arg1,arg2,arg3,arg4,arg5);
  {
    jfloat jvalue = (jfloat)temp3;
    (*jenv)->SetFloatArrayRegion(jenv, jarg3, 0, 1, &jvalue);
  }
  {
    jfloat jvalue = (jfloat)temp4;
    (*jenv)->SetFloatArrayRegion(jenv, jarg4, 0, 1, &jvalue);
  }
  {
    jfloat jvalue = (jfloat)temp5;
    (*jenv)->SetFloatArrayRegion(jenv, jarg5, 0, 1, &jvalue);
  }
  
  
  
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1get_1gyroscope_1frame(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jfloatArray jarg3, jfloatArray jarg4, jfloatArray jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  float temp3 ;
  float temp4 ;
  float temp5 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp3 = (float)0;
    arg3 = &temp3; 
  }
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp4 = (float)0;
    arg4 = &temp4; 
  }
  {
    if (!jarg5) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg5) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp5 = (float)0;
    arg5 = &temp5; 
  }
  PSMove_get_gyroscope_frame(arg1,arg2,arg3,arg4,arg5);
  {
    jfloat jvalue = (jfloat)temp3;
    (*jenv)->SetFloatArrayRegion(jenv, jarg3, 0, 1, &jvalue);
  }
  {
    jfloat jvalue = (jfloat)temp4;
    (*jenv)->SetFloatArrayRegion(jenv, jarg4, 0, 1, &jvalue);
  }
  {
    jfloat jvalue = (jfloat)temp5;
    (*jenv)->SetFloatArrayRegion(jenv, jarg5, 0, 1, &jvalue);
  }
  
  
  
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1get_1magnetometer_1vector(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloatArray jarg2, jfloatArray jarg3, jfloatArray jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  float *arg2 = (float *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float temp2 ;
  float temp3 ;
  float temp4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp2 = (float)0;
    arg2 = &temp2; 
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp3 = (float)0;
    arg3 = &temp3; 
  }
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp4 = (float)0;
    arg4 = &temp4; 
  }
  PSMove_get_magnetometer_vector(arg1,arg2,arg3,arg4);
  {
    jfloat jvalue = (jfloat)temp2;
    (*jenv)->SetFloatArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  {
    jfloat jvalue = (jfloat)temp3;
    (*jenv)->SetFloatArrayRegion(jenv, jarg3, 0, 1, &jvalue);
  }
  {
    jfloat jvalue = (jfloat)temp4;
    (*jenv)->SetFloatArrayRegion(jenv, jarg4, 0, 1, &jvalue);
  }
  
  
  
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1enable_1orientation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (int)jarg2; 
  PSMove_enable_orientation(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1has_1orientation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_has_orientation(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1has_1calibration(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_has_calibration(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1get_1orientation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jfloatArray jarg2, jfloatArray jarg3, jfloatArray jarg4, jfloatArray jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  float *arg2 = (float *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  float temp2 ;
  float temp3 ;
  float temp4 ;
  float temp5 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp2 = (float)0;
    arg2 = &temp2; 
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp3 = (float)0;
    arg3 = &temp3; 
  }
  {
    if (!jarg4) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg4) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp4 = (float)0;
    arg4 = &temp4; 
  }
  {
    if (!jarg5) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg5) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp5 = (float)0;
    arg5 = &temp5; 
  }
  PSMove_get_orientation(arg1,arg2,arg3,arg4,arg5);
  {
    jfloat jvalue = (jfloat)temp2;
    (*jenv)->SetFloatArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  {
    jfloat jvalue = (jfloat)temp3;
    (*jenv)->SetFloatArrayRegion(jenv, jarg3, 0, 1, &jvalue);
  }
  {
    jfloat jvalue = (jfloat)temp4;
    (*jenv)->SetFloatArrayRegion(jenv, jarg4, 0, 1, &jvalue);
  }
  {
    jfloat jvalue = (jfloat)temp5;
    (*jenv)->SetFloatArrayRegion(jenv, jarg5, 0, 1, &jvalue);
  }
  
  
  
  
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1reset_1orientation(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  PSMove_reset_orientation(arg1);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1set_1leds(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2, jint jarg3, jint jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  PSMove_set_leds(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1set_1rumble(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (int)jarg2; 
  PSMove_set_rumble(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1update_1leds(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_update_leds(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1set_1rate_1limiting(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = (int)jarg2; 
  PSMove_set_rate_limiting(arg1,arg2);
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1pair(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_pair(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1pair_1custom(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)PSMove_pair_custom(arg1,(char const *)arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jstring JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1get_1serial(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (char *)PSMove_get_serial(arg1);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1is_1remote(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_is_remote(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1poll(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_poll(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1get_1buttons(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_get_buttons(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1get_1button_1events(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlongArray jarg2, jlongArray jarg3) {
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  unsigned int temp2 ;
  unsigned int temp3 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp2 = (unsigned int)0;
    arg2 = &temp2; 
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return ;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return ;
    }
    temp3 = (unsigned int)0;
    arg3 = &temp3; 
  }
  PSMove_get_button_events(arg1,arg2,arg3);
  {
    jlong jvalue = (jlong)temp2;
    (*jenv)->SetLongArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  {
    jlong jvalue = (jlong)temp3;
    (*jenv)->SetLongArrayRegion(jenv, jarg3, 0, 1, &jvalue);
  }
  
  
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1get_1battery(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_get_battery(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1get_1temperature(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_get_temperature(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jfloat JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1get_1temperature_1in_1celsius(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jfloat jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  float result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (float)PSMove_get_temperature_in_celsius(arg1);
  jresult = (jfloat)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_PSMove_1get_1trigger(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(PSMove **)&jarg1; 
  result = (int)PSMove_get_trigger(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_delete_1PSMove(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(PSMove **)&jarg1; 
  delete_PSMove(arg1);
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_init(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jint jresult = 0 ;
  enum PSMove_Version arg1 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  arg1 = (enum PSMove_Version)jarg1; 
  result = (int)init(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_set_1remote_1config(JNIEnv *jenv, jclass jcls, jint jarg1) {
  enum PSMove_RemoteConfig arg1 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (enum PSMove_RemoteConfig)jarg1; 
  set_remote_config(arg1);
}


SWIGEXPORT jint JNICALL Java_io_thp_psmove_psmoveapiJNI_count_1connected(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int)count_connected();
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_io_thp_psmove_psmoveapiJNI_reinit(JNIEnv *jenv, jclass jcls) {
  (void)jenv;
  (void)jcls;
  reinit();
}


#ifdef __cplusplus
}
#endif

