/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.thp.psmove;

public enum PSMove_Version {
  PSMOVE_CURRENT_VERSION(0x030001);

  public final int swigValue() {
    return swigValue;
  }

  public static PSMove_Version swigToEnum(int swigValue) {
    PSMove_Version[] swigValues = PSMove_Version.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (PSMove_Version swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + PSMove_Version.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private PSMove_Version() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private PSMove_Version(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private PSMove_Version(PSMove_Version swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

