/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */


#ifndef SWIGCSHARP
#define SWIGCSHARP
#endif


/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stdlib.h>
#include <string.h>
#include <stdio.h>


/* Support for throwing C# exceptions from C/C++. There are two types: 
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
  SWIG_CSharpApplicationException,
  SWIG_CSharpArithmeticException,
  SWIG_CSharpDivideByZeroException,
  SWIG_CSharpIndexOutOfRangeException,
  SWIG_CSharpInvalidCastException,
  SWIG_CSharpInvalidOperationException,
  SWIG_CSharpIOException,
  SWIG_CSharpNullReferenceException,
  SWIG_CSharpOutOfMemoryException,
  SWIG_CSharpOverflowException,
  SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
  SWIG_CSharpArgumentException,
  SWIG_CSharpArgumentNullException,
  SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void (SWIGSTDCALL* SWIG_CSharpExceptionCallback_t)(const char *);
typedef void (SWIGSTDCALL* SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
  SWIG_CSharpExceptionCodes code;
  SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
  SWIG_CSharpExceptionArgumentCodes code;
  SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
  { SWIG_CSharpApplicationException, NULL },
  { SWIG_CSharpArithmeticException, NULL },
  { SWIG_CSharpDivideByZeroException, NULL },
  { SWIG_CSharpIndexOutOfRangeException, NULL },
  { SWIG_CSharpInvalidCastException, NULL },
  { SWIG_CSharpInvalidOperationException, NULL },
  { SWIG_CSharpIOException, NULL },
  { SWIG_CSharpNullReferenceException, NULL },
  { SWIG_CSharpOutOfMemoryException, NULL },
  { SWIG_CSharpOverflowException, NULL },
  { SWIG_CSharpSystemException, NULL }
};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
  { SWIG_CSharpArgumentException, NULL },
  { SWIG_CSharpArgumentNullException, NULL },
  { SWIG_CSharpArgumentOutOfRangeException, NULL }
};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
  SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions)/sizeof(SWIG_CSharpException_t)) {
    callback = SWIG_csharp_exceptions[code].callback;
  }
  callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg, const char *param_name) {
  SWIG_CSharpExceptionArgumentCallback_t callback = SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
  if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument)/sizeof(SWIG_CSharpExceptionArgument_t)) {
    callback = SWIG_csharp_exceptions_argument[code].callback;
  }
  callback(msg, param_name);
}


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionCallbacks_psmoveapi_csharp(
                                                SWIG_CSharpExceptionCallback_t applicationCallback,
                                                SWIG_CSharpExceptionCallback_t arithmeticCallback,
                                                SWIG_CSharpExceptionCallback_t divideByZeroCallback, 
                                                SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback, 
                                                SWIG_CSharpExceptionCallback_t invalidCastCallback,
                                                SWIG_CSharpExceptionCallback_t invalidOperationCallback,
                                                SWIG_CSharpExceptionCallback_t ioCallback,
                                                SWIG_CSharpExceptionCallback_t nullReferenceCallback,
                                                SWIG_CSharpExceptionCallback_t outOfMemoryCallback, 
                                                SWIG_CSharpExceptionCallback_t overflowCallback, 
                                                SWIG_CSharpExceptionCallback_t systemCallback) {
  SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
  SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
  SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
  SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
  SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
  SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
  SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterExceptionArgumentCallbacks_psmoveapi_csharp(
                                                SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
  SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}


/* Callback for returning strings to C# without leaking memory */
typedef char * (SWIGSTDCALL* SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;


#ifdef __cplusplus
extern "C" 
#endif
SWIGEXPORT void SWIGSTDCALL SWIGRegisterStringCallback_psmoveapi_csharp(SWIG_CSharpStringHelperCallback callback) {
  SWIG_csharp_string_callback = callback;
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, ""); return nullreturn; } else



 /**
 * PS Move API - An interface for the PS Move Motion Controller
 * Copyright (c) 2011, 2012 Thomas Perl <m@thp.io>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 *    1. Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *
 *    2. Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 **/


#include "psmove.h"
#include "psmove_tracker.h"
#include "psmove_fusion.h"


SWIGINTERN PSMove *new_PSMove__SWIG_0(void){
        return psmove_connect_by_id(0);
    }
SWIGINTERN PSMove *new_PSMove__SWIG_1(int id){
        return psmove_connect_by_id(id);
    }
SWIGINTERN void PSMove_enable_orientation(PSMove *self,int enabled){
        psmove_enable_orientation(self, enabled);
    }
SWIGINTERN int PSMove_has_orientation(PSMove *self){
        return psmove_has_orientation(self);
    }
SWIGINTERN int PSMove_has_calibration(PSMove *self){
        return psmove_has_calibration(self);
    }
SWIGINTERN void PSMove_reset_orientation(PSMove *self){
        psmove_reset_orientation(self);
    }
SWIGINTERN void PSMove_set_leds(PSMove *self,int r,int g,int b){
        psmove_set_leds(self, r, g, b);
    }
SWIGINTERN void PSMove_set_rumble(PSMove *self,int rumble){
        psmove_set_rumble(self, rumble);
    }
SWIGINTERN int PSMove_update_leds(PSMove *self){
        return psmove_update_leds(self);
    }
SWIGINTERN void PSMove_set_rate_limiting(PSMove *self,int enabled){
        psmove_set_rate_limiting(self, enabled);
    }
SWIGINTERN int PSMove_pair(PSMove *self){
        return psmove_pair(self);
    }
SWIGINTERN int PSMove_pair_custom(PSMove *self,char const *btaddr){
        return psmove_pair_custom(self, btaddr);
    }
SWIGINTERN char const *PSMove_get_serial(PSMove *self){
        static char *result = NULL;
        if (result != NULL) {
            free(result);
        }
        result = psmove_get_serial(self);
        return result;
    }
SWIGINTERN int PSMove_is_remote(PSMove *self){
        return psmove_is_remote(self);
    }
SWIGINTERN int PSMove_poll(PSMove *self){
        return psmove_poll(self);
    }
SWIGINTERN int PSMove_get_buttons(PSMove *self){
        return psmove_get_buttons(self);
    }
SWIGINTERN int PSMove_get_battery(PSMove *self){
        return psmove_get_battery(self);
    }
SWIGINTERN int PSMove_get_temperature(PSMove *self){
        return psmove_get_temperature(self);
    }
SWIGINTERN float PSMove_get_temperature_in_celsius(PSMove *self){
        return psmove_get_temperature_in_celsius(self);
    }
SWIGINTERN int PSMove_get_trigger(PSMove *self){
        return psmove_get_trigger(self);
    }
SWIGINTERN void delete_PSMove(PSMove *self){
        psmove_disconnect(self);
    }


void
PSMove_get_accelerometer_frame(PSMove *move, enum PSMove_Frame frame,
    float *x, float *y, float *z) {
    psmove_get_accelerometer_frame(move, frame, x, y, z);
}

void
PSMove_get_gyroscope_frame(PSMove *move, enum PSMove_Frame frame,
    float *x, float *y, float *z) {
    psmove_get_gyroscope_frame(move, frame, x, y, z);
}

void
PSMove_get_magnetometer_vector(PSMove *move, float *x, float *y, float *z)
{
    psmove_get_magnetometer_vector(move, x, y, z);
}

void
PSMove_get_orientation(PSMove *move, float *w, float *x, float *y, float *z)
{
    psmove_get_orientation(move, w, x, y, z);
}

void
PSMove_get_button_events(PSMove *move,
    unsigned int *pressed, unsigned int *released)
{
    psmove_get_button_events(move, pressed, released);
}

int
PSMove_connection_type_get(PSMove *move) {
    return psmove_connection_type(move);
}

int
PSMove_ax_get(PSMove *move) {
    int result;
    psmove_get_accelerometer(move, &result, NULL, NULL);
    return result;
}

int
PSMove_ay_get(PSMove *move) {
    int result;
    psmove_get_accelerometer(move, NULL, &result, NULL);
    return result;
}

int
PSMove_az_get(PSMove *move) {
    int result;
    psmove_get_accelerometer(move, NULL, NULL, &result);
    return result;
}

int
PSMove_gx_get(PSMove *move) {
    int result;
    psmove_get_gyroscope(move, &result, NULL, NULL);
    return result;
}

int
PSMove_gy_get(PSMove *move) {
    int result;
    psmove_get_gyroscope(move, NULL, &result, NULL);
    return result;
}

int
PSMove_gz_get(PSMove *move) {
    int result;
    psmove_get_gyroscope(move, NULL, NULL, &result);
    return result;
}


int
PSMove_mx_get(PSMove *move) {
    int result;
    psmove_get_magnetometer(move, &result, NULL, NULL);
    return result;
}

int
PSMove_my_get(PSMove *move) {
    int result;
    psmove_get_magnetometer(move, NULL, &result, NULL);
    return result;
}

int
PSMove_mz_get(PSMove *move) {
    int result;
    psmove_get_magnetometer(move, NULL, NULL, &result);
    return result;
}

int
init(enum PSMove_Version version)
{
    return psmove_init(version);
}

void set_remote_config(enum PSMove_RemoteConfig config)
{
    return psmove_set_remote_config(config);
}

int count_connected()
{
    return psmove_count_connected();
}

void reinit()
{
    return psmove_reinit();
}

#ifdef PSMOVE_BUILD_TRACKER

int
PSMoveTrackerRGBImage_size_get(PSMoveTrackerRGBImage *image)
{
    return 3 * image->width * image->height;
}

float
PSMoveTracker_dimming_get(PSMoveTracker *tracker)
{
    return psmove_tracker_get_dimming(tracker);
}

void
PSMoveTracker_dimming_set(PSMoveTracker *tracker, float dimming)
{
    psmove_tracker_set_dimming(tracker, dimming);
}

void
PSMoveTracker_exposure_set(PSMoveTracker *tracker,
    enum PSMoveTracker_Exposure exposure)
{
    psmove_tracker_set_exposure(tracker, exposure);
}

enum PSMoveTracker_Exposure
PSMoveTracker_exposure_get(PSMoveTracker *tracker)
{
    return psmove_tracker_get_exposure(tracker);
}

void
PSMoveTracker_get_color(PSMoveTracker *tracker, PSMove *move,
    unsigned char *r, unsigned char *g, unsigned char *b)
{
    psmove_tracker_get_color(tracker, move, r, g, b);
}

void
PSMoveTracker_get_camera_color(PSMoveTracker *tracker, PSMove *move,
    unsigned char *r, unsigned char *g, unsigned char *b)
{
    psmove_tracker_get_camera_color(tracker, move, r, g, b);
}

void
PSMoveTracker_get_position(PSMoveTracker *tracker, PSMove *move,
    float *x, float *y, float *radius)
{
    psmove_tracker_get_position(tracker, move, x, y, radius);
}

void
PSMoveTracker_get_size(PSMoveTracker *tracker, int *width, int *height)
{
    return psmove_tracker_get_size(tracker, width, height);
}

void
PSMoveFusion_get_position(PSMoveFusion *fusion, PSMove *move,
            float *x, float *y, float *z)
{
    psmove_fusion_get_position(fusion, move, x, y, z);
}

#endif /* PSMOVE_BUILD_TRACKER */



#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMOVE_EXT_DATA_BUF_SIZE_get___() {
  int jresult ;
  int result;
  
  result = (int)(5);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_Ext_Device_Info_dev_id_set___(void * jarg1, unsigned short jarg2) {
  PSMove_Ext_Device_Info *arg1 = (PSMove_Ext_Device_Info *) 0 ;
  unsigned short arg2 ;
  
  arg1 = (PSMove_Ext_Device_Info *)jarg1; 
  arg2 = (unsigned short)jarg2; 
  if (arg1) (arg1)->dev_id = arg2;
}


SWIGEXPORT unsigned short SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_Ext_Device_Info_dev_id_get___(void * jarg1) {
  unsigned short jresult ;
  PSMove_Ext_Device_Info *arg1 = (PSMove_Ext_Device_Info *) 0 ;
  unsigned short result;
  
  arg1 = (PSMove_Ext_Device_Info *)jarg1; 
  result = (unsigned short) ((arg1)->dev_id);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_Ext_Device_Info_dev_info_set___(void * jarg1, void * jarg2) {
  PSMove_Ext_Device_Info *arg1 = (PSMove_Ext_Device_Info *) 0 ;
  unsigned char *arg2 ;
  
  arg1 = (PSMove_Ext_Device_Info *)jarg1; 
  arg2 = (unsigned char *)jarg2; 
  {
    size_t ii;
    unsigned char *b = (unsigned char *) arg1->dev_info;
    for (ii = 0; ii < (size_t)38; ii++) b[ii] = *((unsigned char *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_Ext_Device_Info_dev_info_get___(void * jarg1) {
  void * jresult ;
  PSMove_Ext_Device_Info *arg1 = (PSMove_Ext_Device_Info *) 0 ;
  unsigned char *result = 0 ;
  
  arg1 = (PSMove_Ext_Device_Info *)jarg1; 
  result = (unsigned char *)(unsigned char *) ((arg1)->dev_info);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove_new_PSMove_Ext_Device_Info___() {
  void * jresult ;
  PSMove_Ext_Device_Info *result = 0 ;
  
  result = (PSMove_Ext_Device_Info *)calloc(1, sizeof(PSMove_Ext_Device_Info));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_delete_PSMove_Ext_Device_Info___(void * jarg1) {
  PSMove_Ext_Device_Info *arg1 = (PSMove_Ext_Device_Info *) 0 ;
  
  arg1 = (PSMove_Ext_Device_Info *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisVector_x_set___(void * jarg1, float jarg2) {
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float arg2 ;
  
  arg1 = (struct _PSMove_3AxisVector *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->x = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisVector_x_get___(void * jarg1) {
  float jresult ;
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float result;
  
  arg1 = (struct _PSMove_3AxisVector *)jarg1; 
  result = (float) ((arg1)->x);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisVector_y_set___(void * jarg1, float jarg2) {
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float arg2 ;
  
  arg1 = (struct _PSMove_3AxisVector *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->y = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisVector_y_get___(void * jarg1) {
  float jresult ;
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float result;
  
  arg1 = (struct _PSMove_3AxisVector *)jarg1; 
  result = (float) ((arg1)->y);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisVector_z_set___(void * jarg1, float jarg2) {
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float arg2 ;
  
  arg1 = (struct _PSMove_3AxisVector *)jarg1; 
  arg2 = (float)jarg2; 
  if (arg1) (arg1)->z = arg2;
}


SWIGEXPORT float SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisVector_z_get___(void * jarg1) {
  float jresult ;
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float result;
  
  arg1 = (struct _PSMove_3AxisVector *)jarg1; 
  result = (float) ((arg1)->z);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisVector_v_set___(void * jarg1, void * jarg2) {
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float *arg2 ;
  
  arg1 = (struct _PSMove_3AxisVector *)jarg1; 
  arg2 = (float *)jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->v;
    for (ii = 0; ii < (size_t)3; ii++) b[ii] = *((float *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisVector_v_get___(void * jarg1) {
  void * jresult ;
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  float *result = 0 ;
  
  arg1 = (struct _PSMove_3AxisVector *)jarg1; 
  result = (float *)(float *) ((arg1)->v);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove_new__PSMove_3AxisVector___() {
  void * jresult ;
  struct _PSMove_3AxisVector *result = 0 ;
  
  result = (struct _PSMove_3AxisVector *)calloc(1, sizeof(struct _PSMove_3AxisVector));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_delete__PSMove_3AxisVector___(void * jarg1) {
  struct _PSMove_3AxisVector *arg1 = (struct _PSMove_3AxisVector *) 0 ;
  
  arg1 = (struct _PSMove_3AxisVector *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisTransform_row0_set___(void * jarg1, void * jarg2) {
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *arg2 ;
  
  arg1 = (struct _PSMove_3AxisTransform *)jarg1; 
  arg2 = (float *)jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->row0;
    for (ii = 0; ii < (size_t)3; ii++) b[ii] = *((float *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisTransform_row0_get___(void * jarg1) {
  void * jresult ;
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *result = 0 ;
  
  arg1 = (struct _PSMove_3AxisTransform *)jarg1; 
  result = (float *)(float *) ((arg1)->row0);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisTransform_row1_set___(void * jarg1, void * jarg2) {
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *arg2 ;
  
  arg1 = (struct _PSMove_3AxisTransform *)jarg1; 
  arg2 = (float *)jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->row1;
    for (ii = 0; ii < (size_t)3; ii++) b[ii] = *((float *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisTransform_row1_get___(void * jarg1) {
  void * jresult ;
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *result = 0 ;
  
  arg1 = (struct _PSMove_3AxisTransform *)jarg1; 
  result = (float *)(float *) ((arg1)->row1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisTransform_row2_set___(void * jarg1, void * jarg2) {
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *arg2 ;
  
  arg1 = (struct _PSMove_3AxisTransform *)jarg1; 
  arg2 = (float *)jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->row2;
    for (ii = 0; ii < (size_t)3; ii++) b[ii] = *((float *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisTransform_row2_get___(void * jarg1) {
  void * jresult ;
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *result = 0 ;
  
  arg1 = (struct _PSMove_3AxisTransform *)jarg1; 
  result = (float *)(float *) ((arg1)->row2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisTransform_m_set___(void * jarg1, void * jarg2) {
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *arg2 ;
  
  arg1 = (struct _PSMove_3AxisTransform *)jarg1; 
  arg2 = (float *)jarg2; 
  {
    size_t ii;
    float *b = (float *) arg1->m;
    for (ii = 0; ii < (size_t)9; ii++) b[ii] = *((float *) arg2 + ii);
  }
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove__PSMove_3AxisTransform_m_get___(void * jarg1) {
  void * jresult ;
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  float *result = 0 ;
  
  arg1 = (struct _PSMove_3AxisTransform *)jarg1; 
  result = (float *)(float *) ((arg1)->m);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove_new__PSMove_3AxisTransform___() {
  void * jresult ;
  struct _PSMove_3AxisTransform *result = 0 ;
  
  result = (struct _PSMove_3AxisTransform *)calloc(1, sizeof(struct _PSMove_3AxisTransform));
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_delete__PSMove_3AxisTransform___(void * jarg1) {
  struct _PSMove_3AxisTransform *arg1 = (struct _PSMove_3AxisTransform *) 0 ;
  
  arg1 = (struct _PSMove_3AxisTransform *)jarg1; 
  free((char *) arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_init___(int jarg1) {
  int jresult ;
  enum PSMove_Version arg1 ;
  enum PSMove_Bool result;
  
  arg1 = (enum PSMove_Version)jarg1; 
  result = (enum PSMove_Bool)psmove_init(arg1);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_set_remote_config___(int jarg1) {
  enum PSMove_RemoteConfig arg1 ;
  
  arg1 = (enum PSMove_RemoteConfig)jarg1; 
  psmove_set_remote_config(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_count_connected___() {
  int jresult ;
  int result;
  
  result = (int)psmove_count_connected();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove_psmove_connect___() {
  void * jresult ;
  PSMove *result = 0 ;
  
  result = (PSMove *)psmove_connect();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove_psmove_connect_by_id___(int jarg1) {
  void * jresult ;
  int arg1 ;
  PSMove *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (PSMove *)psmove_connect_by_id(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_connection_type___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Connection_Type result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Connection_Type)psmove_connection_type(arg1);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_is_remote___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Bool)psmove_is_remote(arg1);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_serial___(void * jarg1) {
  char * jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  char *result = 0 ;
  
  arg1 = (PSMove *)jarg1; 
  result = (char *)psmove_get_serial(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_pair___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Bool)psmove_pair(arg1);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_pair_custom___(void * jarg1, char * jarg2) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  char *arg2 = (char *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (enum PSMove_Bool)psmove_pair_custom(arg1,(char const *)arg2);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_set_rate_limiting___(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Bool)jarg2; 
  psmove_set_rate_limiting(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_set_leds___(void * jarg1, unsigned char jarg2, unsigned char jarg3, unsigned char jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned char arg2 ;
  unsigned char arg3 ;
  unsigned char arg4 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (unsigned char)jarg2; 
  arg3 = (unsigned char)jarg3; 
  arg4 = (unsigned char)jarg4; 
  psmove_set_leds(arg1,arg2,arg3,arg4);
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_set_led_pwm_frequency___(void * jarg1, unsigned long jarg2) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned long arg2 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (unsigned long)jarg2; 
  result = (enum PSMove_Bool)psmove_set_led_pwm_frequency(arg1,arg2);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_set_rumble___(void * jarg1, unsigned char jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned char arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (unsigned char)jarg2; 
  psmove_set_rumble(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_update_leds___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Update_Result result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Update_Result)psmove_update_leds(arg1);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_poll___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)psmove_poll(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_ext_data___(void * jarg1, void * jarg2) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_Ext_Data *arg2 = (PSMove_Ext_Data *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (PSMove_Ext_Data *)jarg2; 
  result = (enum PSMove_Bool)psmove_get_ext_data(arg1,(unsigned char (*)[5])arg2);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_send_ext_data___(void * jarg1, void * jarg2, unsigned char jarg3) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned char *arg2 = (unsigned char *) 0 ;
  unsigned char arg3 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (unsigned char *)jarg2; 
  arg3 = (unsigned char)jarg3; 
  result = (enum PSMove_Bool)psmove_send_ext_data(arg1,(unsigned char const *)arg2,arg3);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT unsigned int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_buttons___(void * jarg1) {
  unsigned int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (unsigned int)psmove_get_buttons(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_button_events___(void * jarg1, void * jarg2, void * jarg3) {
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (unsigned int *)jarg2; 
  arg3 = (unsigned int *)jarg3; 
  psmove_get_button_events(arg1,arg2,arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_is_ext_connected___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Bool)psmove_is_ext_connected(arg1);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_ext_device_info___(void * jarg1, void * jarg2) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_Ext_Device_Info *arg2 = (PSMove_Ext_Device_Info *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (PSMove_Ext_Device_Info *)jarg2; 
  result = (enum PSMove_Bool)psmove_get_ext_device_info(arg1,arg2);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_battery___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Battery_Level result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Battery_Level)psmove_get_battery(arg1);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_temperature___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)psmove_get_temperature(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT float SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_temperature_in_celsius___(void * jarg1) {
  float jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  float result;
  
  arg1 = (PSMove *)jarg1; 
  result = (float)psmove_get_temperature_in_celsius(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT unsigned char SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_trigger___(void * jarg1) {
  unsigned char jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned char result;
  
  arg1 = (PSMove *)jarg1; 
  result = (unsigned char)psmove_get_trigger(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_accelerometer___(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int *arg4 = (int *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  arg4 = (int *)jarg4; 
  psmove_get_accelerometer(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_gyroscope___(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int *arg4 = (int *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  arg4 = (int *)jarg4; 
  psmove_get_gyroscope(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_magnetometer___(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int *arg4 = (int *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int *)jarg2; 
  arg3 = (int *)jarg3; 
  arg4 = (int *)jarg4; 
  psmove_get_magnetometer(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_accelerometer_frame___(void * jarg1, int jarg2, void * jarg3, void * jarg4, void * jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  psmove_get_accelerometer_frame(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_gyroscope_frame___(void * jarg1, int jarg2, void * jarg3, void * jarg4, void * jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  psmove_get_gyroscope_frame(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_magnetometer_vector___(void * jarg1, void * jarg2, void * jarg3, void * jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  float *arg2 = (float *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (float *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  psmove_get_magnetometer_vector(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_magnetometer_3axisvector___(void * jarg1, void * jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (PSMove_3AxisVector *)jarg2; 
  psmove_get_magnetometer_3axisvector(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_reset_magnetometer_calibration___(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  psmove_reset_magnetometer_calibration(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_save_magnetometer_calibration___(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  psmove_save_magnetometer_calibration(arg1);
}


SWIGEXPORT float SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_magnetometer_calibration_range___(void * jarg1) {
  float jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  float result;
  
  arg1 = (PSMove *)jarg1; 
  result = (float)psmove_get_magnetometer_calibration_range(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_has_calibration___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Bool)psmove_has_calibration(arg1);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_dump_calibration___(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  psmove_dump_calibration(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_enable_orientation___(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Bool)jarg2; 
  psmove_enable_orientation(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_has_orientation___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Bool result;
  
  arg1 = (PSMove *)jarg1; 
  result = (enum PSMove_Bool)psmove_has_orientation(arg1);
  jresult = (int)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_orientation___(void * jarg1, void * jarg2, void * jarg3, void * jarg4, void * jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  float *arg2 = (float *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (float *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  psmove_get_orientation(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_reset_orientation___(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  psmove_reset_orientation(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_set_orientation_fusion_type___(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMoveOrientation_Fusion_Type arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMoveOrientation_Fusion_Type)jarg2; 
  psmove_set_orientation_fusion_type(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_set_calibration_pose___(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_CalibrationPose_Type arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_CalibrationPose_Type)jarg2; 
  psmove_set_calibration_pose(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_set_calibration_transform___(void * jarg1, void * jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisTransform *arg2 = (PSMove_3AxisTransform *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (PSMove_3AxisTransform *)jarg2; 
  psmove_set_calibration_transform(arg1,(struct _PSMove_3AxisTransform const *)arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_identity_gravity_calibration_direction___(void * jarg1, void * jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (PSMove_3AxisVector *)jarg2; 
  psmove_get_identity_gravity_calibration_direction(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_transformed_gravity_calibration_direction___(void * jarg1, void * jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (PSMove_3AxisVector *)jarg2; 
  psmove_get_transformed_gravity_calibration_direction(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_identity_magnetometer_calibration_direction___(void * jarg1, void * jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (PSMove_3AxisVector *)jarg2; 
  psmove_get_identity_magnetometer_calibration_direction(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_transformed_magnetometer_calibration_direction___(void * jarg1, void * jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (PSMove_3AxisVector *)jarg2; 
  psmove_get_transformed_magnetometer_calibration_direction(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_set_magnetometer_calibration_direction___(void * jarg1, void * jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (PSMove_3AxisVector *)jarg2; 
  psmove_set_magnetometer_calibration_direction(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_set_sensor_data_basis___(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_SensorDataBasis_Type arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_SensorDataBasis_Type)jarg2; 
  psmove_set_sensor_data_basis(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_set_sensor_data_transform___(void * jarg1, void * jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisTransform *arg2 = (PSMove_3AxisTransform *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (PSMove_3AxisTransform *)jarg2; 
  psmove_set_sensor_data_transform(arg1,(struct _PSMove_3AxisTransform const *)arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_transformed_magnetometer_direction___(void * jarg1, void * jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  PSMove_3AxisVector *arg2 = (PSMove_3AxisVector *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (PSMove_3AxisVector *)jarg2; 
  psmove_get_transformed_magnetometer_direction(arg1,arg2);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_transformed_accelerometer_frame_3axisvector___(void * jarg1, int jarg2, void * jarg3) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  PSMove_3AxisVector *arg3 = (PSMove_3AxisVector *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = (PSMove_3AxisVector *)jarg3; 
  psmove_get_transformed_accelerometer_frame_3axisvector(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_transformed_accelerometer_frame_direction___(void * jarg1, int jarg2, void * jarg3) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  PSMove_3AxisVector *arg3 = (PSMove_3AxisVector *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = (PSMove_3AxisVector *)jarg3; 
  psmove_get_transformed_accelerometer_frame_direction(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_get_transformed_gyroscope_frame_3axisvector___(void * jarg1, int jarg2, void * jarg3) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  PSMove_3AxisVector *arg3 = (PSMove_3AxisVector *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = (PSMove_3AxisVector *)jarg3; 
  psmove_get_transformed_gyroscope_frame_3axisvector(arg1,arg2,arg3);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_disconnect___(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  psmove_disconnect(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_psmove_reinit___() {
  psmove_reinit();
}


SWIGEXPORT long SWIGSTDCALL CSharp_iofthpfpsmove_psmove_util_get_ticks___() {
  long jresult ;
  long result;
  
  result = (long)psmove_util_get_ticks();
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_iofthpfpsmove_psmove_util_get_data_dir___() {
  char * jresult ;
  char *result = 0 ;
  
  result = (char *)psmove_util_get_data_dir();
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_iofthpfpsmove_psmove_util_get_file_path___(char * jarg1) {
  char * jresult ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (char *)psmove_util_get_file_path((char const *)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_iofthpfpsmove_psmove_util_get_system_file_path___(char * jarg1) {
  char * jresult ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (char *)psmove_util_get_system_file_path((char const *)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_psmove_util_get_env_int___(char * jarg1) {
  int jresult ;
  char *arg1 = (char *) 0 ;
  int result;
  
  arg1 = (char *)jarg1; 
  result = (int)psmove_util_get_env_int((char const *)arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_iofthpfpsmove_psmove_util_get_env_string___(char * jarg1) {
  char * jresult ;
  char *arg1 = (char *) 0 ;
  char *result = 0 ;
  
  arg1 = (char *)jarg1; 
  result = (char *)psmove_util_get_env_string((char const *)arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_connection_type_get___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_connection_type_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_ax_get___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_ax_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_ay_get___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_ay_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_az_get___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_az_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_gx_get___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_gx_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_gy_get___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_gy_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_gz_get___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_gz_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_mx_get___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_mx_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_my_get___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_my_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_mz_get___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_mz_get(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove_new_PSMove__SWIG_0___() {
  void * jresult ;
  PSMove *result = 0 ;
  
  result = (PSMove *)new_PSMove__SWIG_0();
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void * SWIGSTDCALL CSharp_iofthpfpsmove_new_PSMove__SWIG_1___(int jarg1) {
  void * jresult ;
  int arg1 ;
  PSMove *result = 0 ;
  
  arg1 = (int)jarg1; 
  result = (PSMove *)new_PSMove__SWIG_1(arg1);
  jresult = (void *)result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_get_accelerometer_frame___(void * jarg1, int jarg2, float * jarg3, float * jarg4, float * jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  PSMove_get_accelerometer_frame(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_get_gyroscope_frame___(void * jarg1, int jarg2, float * jarg3, float * jarg4, float * jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  enum PSMove_Frame arg2 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (enum PSMove_Frame)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  PSMove_get_gyroscope_frame(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_get_magnetometer_vector___(void * jarg1, float * jarg2, float * jarg3, float * jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  float *arg2 = (float *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (float *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  PSMove_get_magnetometer_vector(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_enable_orientation___(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  int arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int)jarg2; 
  PSMove_enable_orientation(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_has_orientation___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_has_orientation(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_has_calibration___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_has_calibration(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_get_orientation___(void * jarg1, float * jarg2, float * jarg3, float * jarg4, float * jarg5) {
  PSMove *arg1 = (PSMove *) 0 ;
  float *arg2 = (float *) 0 ;
  float *arg3 = (float *) 0 ;
  float *arg4 = (float *) 0 ;
  float *arg5 = (float *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (float *)jarg2; 
  arg3 = (float *)jarg3; 
  arg4 = (float *)jarg4; 
  arg5 = (float *)jarg5; 
  PSMove_get_orientation(arg1,arg2,arg3,arg4,arg5);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_reset_orientation___(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  PSMove_reset_orientation(arg1);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_set_leds___(void * jarg1, int jarg2, int jarg3, int jarg4) {
  PSMove *arg1 = (PSMove *) 0 ;
  int arg2 ;
  int arg3 ;
  int arg4 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int)jarg2; 
  arg3 = (int)jarg3; 
  arg4 = (int)jarg4; 
  PSMove_set_leds(arg1,arg2,arg3,arg4);
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_set_rumble___(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  int arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int)jarg2; 
  PSMove_set_rumble(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_update_leds___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_update_leds(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_set_rate_limiting___(void * jarg1, int jarg2) {
  PSMove *arg1 = (PSMove *) 0 ;
  int arg2 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (int)jarg2; 
  PSMove_set_rate_limiting(arg1,arg2);
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_pair___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_pair(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_pair_custom___(void * jarg1, char * jarg2) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (char *)jarg2; 
  result = (int)PSMove_pair_custom(arg1,(char const *)arg2);
  jresult = result; 
  return jresult;
}


SWIGEXPORT char * SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_get_serial___(void * jarg1) {
  char * jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  char *result = 0 ;
  
  arg1 = (PSMove *)jarg1; 
  result = (char *)PSMove_get_serial(arg1);
  jresult = SWIG_csharp_string_callback((const char *)result); 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_is_remote___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_is_remote(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_poll___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_poll(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_get_buttons___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_get_buttons(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_get_button_events___(void * jarg1, unsigned int * jarg2, unsigned int * jarg3) {
  PSMove *arg1 = (PSMove *) 0 ;
  unsigned int *arg2 = (unsigned int *) 0 ;
  unsigned int *arg3 = (unsigned int *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  arg2 = (unsigned int *)jarg2; 
  arg3 = (unsigned int *)jarg3; 
  PSMove_get_button_events(arg1,arg2,arg3);
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_get_battery___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_get_battery(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_get_temperature___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_get_temperature(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT float SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_get_temperature_in_celsius___(void * jarg1) {
  float jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  float result;
  
  arg1 = (PSMove *)jarg1; 
  result = (float)PSMove_get_temperature_in_celsius(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_PSMove_get_trigger___(void * jarg1) {
  int jresult ;
  PSMove *arg1 = (PSMove *) 0 ;
  int result;
  
  arg1 = (PSMove *)jarg1; 
  result = (int)PSMove_get_trigger(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_delete_PSMove___(void * jarg1) {
  PSMove *arg1 = (PSMove *) 0 ;
  
  arg1 = (PSMove *)jarg1; 
  delete_PSMove(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_init___(int jarg1) {
  int jresult ;
  enum PSMove_Version arg1 ;
  int result;
  
  arg1 = (enum PSMove_Version)jarg1; 
  result = (int)init(arg1);
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_set_remote_config___(int jarg1) {
  enum PSMove_RemoteConfig arg1 ;
  
  arg1 = (enum PSMove_RemoteConfig)jarg1; 
  set_remote_config(arg1);
}


SWIGEXPORT int SWIGSTDCALL CSharp_iofthpfpsmove_count_connected___() {
  int jresult ;
  int result;
  
  result = (int)count_connected();
  jresult = result; 
  return jresult;
}


SWIGEXPORT void SWIGSTDCALL CSharp_iofthpfpsmove_reinit___() {
  reinit();
}


#ifdef __cplusplus
}
#endif

