//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace io.thp.psmove {

public class PSMove_Ext_Device_Info : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PSMove_Ext_Device_Info(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PSMove_Ext_Device_Info obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PSMove_Ext_Device_Info() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          psmoveapi_csharpPINVOKE.delete_PSMove_Ext_Device_Info(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ushort dev_id {
    set {
      psmoveapi_csharpPINVOKE.PSMove_Ext_Device_Info_dev_id_set(swigCPtr, value);
    } 
    get {
      ushort ret = psmoveapi_csharpPINVOKE.PSMove_Ext_Device_Info_dev_id_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_char dev_info {
    set {
      psmoveapi_csharpPINVOKE.PSMove_Ext_Device_Info_dev_info_set(swigCPtr, SWIGTYPE_p_unsigned_char.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = psmoveapi_csharpPINVOKE.PSMove_Ext_Device_Info_dev_info_get(swigCPtr);
      SWIGTYPE_p_unsigned_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
      return ret;
    } 
  }

  public PSMove_Ext_Device_Info() : this(psmoveapi_csharpPINVOKE.new_PSMove_Ext_Device_Info(), true) {
  }

}

}
