/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.thp.psmove;

public enum PSMoveOrientation_Fusion_Type {
  OrientationFusion_None,
  OrientationFusion_MadgwickIMU,
  OrientationFusion_MadgwickMARG,
  OrientationFusion_ComplementaryMARG;

  public final int swigValue() {
    return swigValue;
  }

  public static PSMoveOrientation_Fusion_Type swigToEnum(int swigValue) {
    PSMoveOrientation_Fusion_Type[] swigValues = PSMoveOrientation_Fusion_Type.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (PSMoveOrientation_Fusion_Type swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + PSMoveOrientation_Fusion_Type.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private PSMoveOrientation_Fusion_Type() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private PSMoveOrientation_Fusion_Type(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private PSMoveOrientation_Fusion_Type(PSMoveOrientation_Fusion_Type swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

