//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace io.thp.psmove {

public enum PSMoveOrientation_Fusion_Type {
  OrientationFusion_None,
  OrientationFusion_MadgwickIMU,
  OrientationFusion_MadgwickMARG,
  OrientationFusion_ComplementaryMARG
}

}
