/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.thp.psmove;

public class PSMove_Ext_Device_Info {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected PSMove_Ext_Device_Info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PSMove_Ext_Device_Info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        psmoveapiJNI.delete_PSMove_Ext_Device_Info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDev_id(int value) {
    psmoveapiJNI.PSMove_Ext_Device_Info_dev_id_set(swigCPtr, this, value);
  }

  public int getDev_id() {
    return psmoveapiJNI.PSMove_Ext_Device_Info_dev_id_get(swigCPtr, this);
  }

  public void setDev_info(SWIGTYPE_p_unsigned_char value) {
    psmoveapiJNI.PSMove_Ext_Device_Info_dev_info_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getDev_info() {
    long cPtr = psmoveapiJNI.PSMove_Ext_Device_Info_dev_info_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public PSMove_Ext_Device_Info() {
    this(psmoveapiJNI.new_PSMove_Ext_Device_Info(), true);
  }

}
