//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace io.thp.psmove {

class psmoveapi_csharpPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="SWIGRegisterExceptionCallbacks_psmoveapi_csharp")]
    public static extern void SWIGRegisterExceptionCallbacks_psmoveapi_csharp(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_psmoveapi_csharp")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_psmoveapi_csharp(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_psmoveapi_csharp(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_psmoveapi_csharp(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(typeof(psmoveapi_csharpPINVOKE)) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(typeof(psmoveapi_csharpPINVOKE)) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="SWIGRegisterStringCallback_psmoveapi_csharp")]
    public static extern void SWIGRegisterStringCallback_psmoveapi_csharp(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_psmoveapi_csharp(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static psmoveapi_csharpPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMOVE_EXT_DATA_BUF_SIZE_get___")]
  public static extern int PSMOVE_EXT_DATA_BUF_SIZE_get();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_Ext_Device_Info_dev_id_set___")]
  public static extern void PSMove_Ext_Device_Info_dev_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, ushort jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_Ext_Device_Info_dev_id_get___")]
  public static extern ushort PSMove_Ext_Device_Info_dev_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_Ext_Device_Info_dev_info_set___")]
  public static extern void PSMove_Ext_Device_Info_dev_info_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_Ext_Device_Info_dev_info_get___")]
  public static extern global::System.IntPtr PSMove_Ext_Device_Info_dev_info_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new_PSMove_Ext_Device_Info___")]
  public static extern global::System.IntPtr new_PSMove_Ext_Device_Info();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete_PSMove_Ext_Device_Info___")]
  public static extern void delete_PSMove_Ext_Device_Info(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_x_set___")]
  public static extern void _PSMove_3AxisVector_x_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_x_get___")]
  public static extern float _PSMove_3AxisVector_x_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_y_set___")]
  public static extern void _PSMove_3AxisVector_y_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_y_get___")]
  public static extern float _PSMove_3AxisVector_y_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_z_set___")]
  public static extern void _PSMove_3AxisVector_z_set(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_z_get___")]
  public static extern float _PSMove_3AxisVector_z_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_v_set___")]
  public static extern void _PSMove_3AxisVector_v_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisVector_v_get___")]
  public static extern global::System.IntPtr _PSMove_3AxisVector_v_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new__PSMove_3AxisVector___")]
  public static extern global::System.IntPtr new__PSMove_3AxisVector();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete__PSMove_3AxisVector___")]
  public static extern void delete__PSMove_3AxisVector(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_row0_set___")]
  public static extern void _PSMove_3AxisTransform_row0_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_row0_get___")]
  public static extern global::System.IntPtr _PSMove_3AxisTransform_row0_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_row1_set___")]
  public static extern void _PSMove_3AxisTransform_row1_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_row1_get___")]
  public static extern global::System.IntPtr _PSMove_3AxisTransform_row1_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_row2_set___")]
  public static extern void _PSMove_3AxisTransform_row2_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_row2_get___")]
  public static extern global::System.IntPtr _PSMove_3AxisTransform_row2_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_m_set___")]
  public static extern void _PSMove_3AxisTransform_m_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove__PSMove_3AxisTransform_m_get___")]
  public static extern global::System.IntPtr _PSMove_3AxisTransform_m_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new__PSMove_3AxisTransform___")]
  public static extern global::System.IntPtr new__PSMove_3AxisTransform();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete__PSMove_3AxisTransform___")]
  public static extern void delete__PSMove_3AxisTransform(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_init___")]
  public static extern int psmove_init(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_remote_config___")]
  public static extern void psmove_set_remote_config(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_count_connected___")]
  public static extern int psmove_count_connected();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_connect___")]
  public static extern global::System.IntPtr psmove_connect();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_connect_by_id___")]
  public static extern global::System.IntPtr psmove_connect_by_id(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_connection_type___")]
  public static extern int psmove_connection_type(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_is_remote___")]
  public static extern int psmove_is_remote(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_serial___")]
  public static extern string psmove_get_serial(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_pair___")]
  public static extern int psmove_pair(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_pair_custom___")]
  public static extern int psmove_pair_custom(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_rate_limiting___")]
  public static extern void psmove_set_rate_limiting(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_leds___")]
  public static extern void psmove_set_leds(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2, byte jarg3, byte jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_led_pwm_frequency___")]
  public static extern int psmove_set_led_pwm_frequency(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_rumble___")]
  public static extern void psmove_set_rumble(global::System.Runtime.InteropServices.HandleRef jarg1, byte jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_update_leds___")]
  public static extern int psmove_update_leds(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_poll___")]
  public static extern int psmove_poll(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_ext_data___")]
  public static extern int psmove_get_ext_data(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_send_ext_data___")]
  public static extern int psmove_send_ext_data(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, byte jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_buttons___")]
  public static extern uint psmove_get_buttons(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_button_events___")]
  public static extern void psmove_get_button_events(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_is_ext_connected___")]
  public static extern int psmove_is_ext_connected(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_ext_device_info___")]
  public static extern int psmove_get_ext_device_info(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_battery___")]
  public static extern int psmove_get_battery(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_temperature___")]
  public static extern int psmove_get_temperature(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_temperature_in_celsius___")]
  public static extern float psmove_get_temperature_in_celsius(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_trigger___")]
  public static extern byte psmove_get_trigger(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_accelerometer___")]
  public static extern void psmove_get_accelerometer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_gyroscope___")]
  public static extern void psmove_get_gyroscope(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_magnetometer___")]
  public static extern void psmove_get_magnetometer(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_accelerometer_frame___")]
  public static extern void psmove_get_accelerometer_frame(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_gyroscope_frame___")]
  public static extern void psmove_get_gyroscope_frame(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_magnetometer_vector___")]
  public static extern void psmove_get_magnetometer_vector(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_magnetometer_3axisvector___")]
  public static extern void psmove_get_magnetometer_3axisvector(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_reset_magnetometer_calibration___")]
  public static extern void psmove_reset_magnetometer_calibration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_save_magnetometer_calibration___")]
  public static extern void psmove_save_magnetometer_calibration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_magnetometer_calibration_range___")]
  public static extern float psmove_get_magnetometer_calibration_range(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_has_calibration___")]
  public static extern int psmove_has_calibration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_dump_calibration___")]
  public static extern void psmove_dump_calibration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_enable_orientation___")]
  public static extern void psmove_enable_orientation(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_has_orientation___")]
  public static extern int psmove_has_orientation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_orientation___")]
  public static extern void psmove_get_orientation(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, global::System.Runtime.InteropServices.HandleRef jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_reset_orientation___")]
  public static extern void psmove_reset_orientation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_orientation_fusion_type___")]
  public static extern void psmove_set_orientation_fusion_type(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_calibration_pose___")]
  public static extern void psmove_set_calibration_pose(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_calibration_transform___")]
  public static extern void psmove_set_calibration_transform(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_identity_gravity_calibration_direction___")]
  public static extern void psmove_get_identity_gravity_calibration_direction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_transformed_gravity_calibration_direction___")]
  public static extern void psmove_get_transformed_gravity_calibration_direction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_identity_magnetometer_calibration_direction___")]
  public static extern void psmove_get_identity_magnetometer_calibration_direction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_transformed_magnetometer_calibration_direction___")]
  public static extern void psmove_get_transformed_magnetometer_calibration_direction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_magnetometer_calibration_direction___")]
  public static extern void psmove_set_magnetometer_calibration_direction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_sensor_data_basis___")]
  public static extern void psmove_set_sensor_data_basis(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_set_sensor_data_transform___")]
  public static extern void psmove_set_sensor_data_transform(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_transformed_magnetometer_direction___")]
  public static extern void psmove_get_transformed_magnetometer_direction(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_transformed_accelerometer_frame_3axisvector___")]
  public static extern void psmove_get_transformed_accelerometer_frame_3axisvector(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_transformed_accelerometer_frame_direction___")]
  public static extern void psmove_get_transformed_accelerometer_frame_direction(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_get_transformed_gyroscope_frame_3axisvector___")]
  public static extern void psmove_get_transformed_gyroscope_frame_3axisvector(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_disconnect___")]
  public static extern void psmove_disconnect(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_reinit___")]
  public static extern void psmove_reinit();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_get_ticks___")]
  public static extern int psmove_util_get_ticks();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_get_data_dir___")]
  public static extern string psmove_util_get_data_dir();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_get_file_path___")]
  public static extern string psmove_util_get_file_path(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_get_system_file_path___")]
  public static extern string psmove_util_get_system_file_path(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_get_env_int___")]
  public static extern int psmove_util_get_env_int(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_psmove_util_get_env_string___")]
  public static extern string psmove_util_get_env_string(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_connection_type_get___")]
  public static extern int PSMove_connection_type_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_ax_get___")]
  public static extern int PSMove_ax_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_ay_get___")]
  public static extern int PSMove_ay_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_az_get___")]
  public static extern int PSMove_az_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_gx_get___")]
  public static extern int PSMove_gx_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_gy_get___")]
  public static extern int PSMove_gy_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_gz_get___")]
  public static extern int PSMove_gz_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_mx_get___")]
  public static extern int PSMove_mx_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_my_get___")]
  public static extern int PSMove_my_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_mz_get___")]
  public static extern int PSMove_mz_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new_PSMove__SWIG_0___")]
  public static extern global::System.IntPtr new_PSMove__SWIG_0();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_new_PSMove__SWIG_1___")]
  public static extern global::System.IntPtr new_PSMove__SWIG_1(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_accelerometer_frame___")]
  public static extern void PSMove_get_accelerometer_frame(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, out float jarg3, out float jarg4, out float jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_gyroscope_frame___")]
  public static extern void PSMove_get_gyroscope_frame(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, out float jarg3, out float jarg4, out float jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_magnetometer_vector___")]
  public static extern void PSMove_get_magnetometer_vector(global::System.Runtime.InteropServices.HandleRef jarg1, out float jarg2, out float jarg3, out float jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_enable_orientation___")]
  public static extern void PSMove_enable_orientation(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_has_orientation___")]
  public static extern int PSMove_has_orientation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_has_calibration___")]
  public static extern int PSMove_has_calibration(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_orientation___")]
  public static extern void PSMove_get_orientation(global::System.Runtime.InteropServices.HandleRef jarg1, out float jarg2, out float jarg3, out float jarg4, out float jarg5);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_reset_orientation___")]
  public static extern void PSMove_reset_orientation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_set_leds___")]
  public static extern void PSMove_set_leds(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, int jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_set_rumble___")]
  public static extern void PSMove_set_rumble(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_update_leds___")]
  public static extern int PSMove_update_leds(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_set_rate_limiting___")]
  public static extern void PSMove_set_rate_limiting(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_pair___")]
  public static extern int PSMove_pair(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_pair_custom___")]
  public static extern int PSMove_pair_custom(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_serial___")]
  public static extern string PSMove_get_serial(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_is_remote___")]
  public static extern int PSMove_is_remote(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_poll___")]
  public static extern int PSMove_poll(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_buttons___")]
  public static extern int PSMove_get_buttons(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_button_events___")]
  public static extern void PSMove_get_button_events(global::System.Runtime.InteropServices.HandleRef jarg1, out uint jarg2, out uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_battery___")]
  public static extern int PSMove_get_battery(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_temperature___")]
  public static extern int PSMove_get_temperature(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_temperature_in_celsius___")]
  public static extern float PSMove_get_temperature_in_celsius(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_PSMove_get_trigger___")]
  public static extern int PSMove_get_trigger(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_delete_PSMove___")]
  public static extern void delete_PSMove(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_init___")]
  public static extern int init(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_set_remote_config___")]
  public static extern void set_remote_config(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_count_connected___")]
  public static extern int count_connected();

  [global::System.Runtime.InteropServices.DllImport("psmoveapi_csharp", EntryPoint="CSharp_iofthpfpsmove_reinit___")]
  public static extern void reinit();
}

}
