//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.10
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace io.thp.psmove {

public class psmoveapi_csharp {
  public static PSMove_Bool psmove_init(PSMove_Version version) {
    PSMove_Bool ret = (PSMove_Bool)psmoveapi_csharpPINVOKE.psmove_init((int)version);
    return ret;
  }

  public static void psmove_set_remote_config(RemoteConfig config) {
    psmoveapi_csharpPINVOKE.psmove_set_remote_config((int)config);
  }

  public static int psmove_count_connected() {
    int ret = psmoveapi_csharpPINVOKE.psmove_count_connected();
    return ret;
  }

  public static PSMove psmove_connect() {
    global::System.IntPtr cPtr = psmoveapi_csharpPINVOKE.psmove_connect();
    PSMove ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMove(cPtr, false);
    return ret;
  }

  public static PSMove psmove_connect_by_id(int id) {
    global::System.IntPtr cPtr = psmoveapi_csharpPINVOKE.psmove_connect_by_id(id);
    PSMove ret = (cPtr == global::System.IntPtr.Zero) ? null : new PSMove(cPtr, false);
    return ret;
  }

  public static ConnectionType psmove_connection_type(PSMove move) {
    ConnectionType ret = (ConnectionType)psmoveapi_csharpPINVOKE.psmove_connection_type(PSMove.getCPtr(move));
    return ret;
  }

  public static PSMove_Bool psmove_is_remote(PSMove move) {
    PSMove_Bool ret = (PSMove_Bool)psmoveapi_csharpPINVOKE.psmove_is_remote(PSMove.getCPtr(move));
    return ret;
  }

  public static string psmove_get_serial(PSMove move) {
    string ret = psmoveapi_csharpPINVOKE.psmove_get_serial(PSMove.getCPtr(move));
    return ret;
  }

  public static PSMove_Bool psmove_pair(PSMove move) {
    PSMove_Bool ret = (PSMove_Bool)psmoveapi_csharpPINVOKE.psmove_pair(PSMove.getCPtr(move));
    return ret;
  }

  public static PSMove_Bool psmove_pair_custom(PSMove move, string new_host_string) {
    PSMove_Bool ret = (PSMove_Bool)psmoveapi_csharpPINVOKE.psmove_pair_custom(PSMove.getCPtr(move), new_host_string);
    return ret;
  }

  public static void psmove_set_rate_limiting(PSMove move, PSMove_Bool enabled) {
    psmoveapi_csharpPINVOKE.psmove_set_rate_limiting(PSMove.getCPtr(move), (int)enabled);
  }

  public static void psmove_set_leds(PSMove move, byte r, byte g, byte b) {
    psmoveapi_csharpPINVOKE.psmove_set_leds(PSMove.getCPtr(move), r, g, b);
  }

  public static PSMove_Bool psmove_set_led_pwm_frequency(PSMove move, uint freq) {
    PSMove_Bool ret = (PSMove_Bool)psmoveapi_csharpPINVOKE.psmove_set_led_pwm_frequency(PSMove.getCPtr(move), freq);
    return ret;
  }

  public static void psmove_set_rumble(PSMove move, byte rumble) {
    psmoveapi_csharpPINVOKE.psmove_set_rumble(PSMove.getCPtr(move), rumble);
  }

  public static PSMove_Update_Result psmove_update_leds(PSMove move) {
    PSMove_Update_Result ret = (PSMove_Update_Result)psmoveapi_csharpPINVOKE.psmove_update_leds(PSMove.getCPtr(move));
    return ret;
  }

  public static int psmove_poll(PSMove move) {
    int ret = psmoveapi_csharpPINVOKE.psmove_poll(PSMove.getCPtr(move));
    return ret;
  }

  public static PSMove_Bool psmove_get_ext_data(PSMove move, SWIGTYPE_p_a_5__unsigned_char data) {
    PSMove_Bool ret = (PSMove_Bool)psmoveapi_csharpPINVOKE.psmove_get_ext_data(PSMove.getCPtr(move), SWIGTYPE_p_a_5__unsigned_char.getCPtr(data));
    return ret;
  }

  public static PSMove_Bool psmove_send_ext_data(PSMove move, SWIGTYPE_p_unsigned_char data, byte length) {
    PSMove_Bool ret = (PSMove_Bool)psmoveapi_csharpPINVOKE.psmove_send_ext_data(PSMove.getCPtr(move), SWIGTYPE_p_unsigned_char.getCPtr(data), length);
    return ret;
  }

  public static uint psmove_get_buttons(PSMove move) {
    uint ret = psmoveapi_csharpPINVOKE.psmove_get_buttons(PSMove.getCPtr(move));
    return ret;
  }

  public static void psmove_get_button_events(PSMove move, SWIGTYPE_p_unsigned_int pressed, SWIGTYPE_p_unsigned_int released) {
    psmoveapi_csharpPINVOKE.psmove_get_button_events(PSMove.getCPtr(move), SWIGTYPE_p_unsigned_int.getCPtr(pressed), SWIGTYPE_p_unsigned_int.getCPtr(released));
  }

  public static PSMove_Bool psmove_is_ext_connected(PSMove move) {
    PSMove_Bool ret = (PSMove_Bool)psmoveapi_csharpPINVOKE.psmove_is_ext_connected(PSMove.getCPtr(move));
    return ret;
  }

  public static PSMove_Bool psmove_get_ext_device_info(PSMove move, PSMove_Ext_Device_Info info) {
    PSMove_Bool ret = (PSMove_Bool)psmoveapi_csharpPINVOKE.psmove_get_ext_device_info(PSMove.getCPtr(move), PSMove_Ext_Device_Info.getCPtr(info));
    return ret;
  }

  public static BatteryLevel psmove_get_battery(PSMove move) {
    BatteryLevel ret = (BatteryLevel)psmoveapi_csharpPINVOKE.psmove_get_battery(PSMove.getCPtr(move));
    return ret;
  }

  public static int psmove_get_temperature(PSMove move) {
    int ret = psmoveapi_csharpPINVOKE.psmove_get_temperature(PSMove.getCPtr(move));
    return ret;
  }

  public static float psmove_get_temperature_in_celsius(PSMove move) {
    float ret = psmoveapi_csharpPINVOKE.psmove_get_temperature_in_celsius(PSMove.getCPtr(move));
    return ret;
  }

  public static byte psmove_get_trigger(PSMove move) {
    byte ret = psmoveapi_csharpPINVOKE.psmove_get_trigger(PSMove.getCPtr(move));
    return ret;
  }

  public static void psmove_get_accelerometer(PSMove move, SWIGTYPE_p_int ax, SWIGTYPE_p_int ay, SWIGTYPE_p_int az) {
    psmoveapi_csharpPINVOKE.psmove_get_accelerometer(PSMove.getCPtr(move), SWIGTYPE_p_int.getCPtr(ax), SWIGTYPE_p_int.getCPtr(ay), SWIGTYPE_p_int.getCPtr(az));
  }

  public static void psmove_get_gyroscope(PSMove move, SWIGTYPE_p_int gx, SWIGTYPE_p_int gy, SWIGTYPE_p_int gz) {
    psmoveapi_csharpPINVOKE.psmove_get_gyroscope(PSMove.getCPtr(move), SWIGTYPE_p_int.getCPtr(gx), SWIGTYPE_p_int.getCPtr(gy), SWIGTYPE_p_int.getCPtr(gz));
  }

  public static void psmove_get_magnetometer(PSMove move, SWIGTYPE_p_int mx, SWIGTYPE_p_int my, SWIGTYPE_p_int mz) {
    psmoveapi_csharpPINVOKE.psmove_get_magnetometer(PSMove.getCPtr(move), SWIGTYPE_p_int.getCPtr(mx), SWIGTYPE_p_int.getCPtr(my), SWIGTYPE_p_int.getCPtr(mz));
  }

  public static void psmove_get_accelerometer_frame(PSMove move, Frame frame, SWIGTYPE_p_float ax, SWIGTYPE_p_float ay, SWIGTYPE_p_float az) {
    psmoveapi_csharpPINVOKE.psmove_get_accelerometer_frame(PSMove.getCPtr(move), (int)frame, SWIGTYPE_p_float.getCPtr(ax), SWIGTYPE_p_float.getCPtr(ay), SWIGTYPE_p_float.getCPtr(az));
  }

  public static void psmove_get_gyroscope_frame(PSMove move, Frame frame, SWIGTYPE_p_float gx, SWIGTYPE_p_float gy, SWIGTYPE_p_float gz) {
    psmoveapi_csharpPINVOKE.psmove_get_gyroscope_frame(PSMove.getCPtr(move), (int)frame, SWIGTYPE_p_float.getCPtr(gx), SWIGTYPE_p_float.getCPtr(gy), SWIGTYPE_p_float.getCPtr(gz));
  }

  public static void psmove_get_magnetometer_vector(PSMove move, SWIGTYPE_p_float mx, SWIGTYPE_p_float my, SWIGTYPE_p_float mz) {
    psmoveapi_csharpPINVOKE.psmove_get_magnetometer_vector(PSMove.getCPtr(move), SWIGTYPE_p_float.getCPtr(mx), SWIGTYPE_p_float.getCPtr(my), SWIGTYPE_p_float.getCPtr(mz));
  }

  public static void psmove_get_magnetometer_3axisvector(PSMove move, _PSMove_3AxisVector out_m) {
    psmoveapi_csharpPINVOKE.psmove_get_magnetometer_3axisvector(PSMove.getCPtr(move), _PSMove_3AxisVector.getCPtr(out_m));
  }

  public static void psmove_reset_magnetometer_calibration(PSMove move) {
    psmoveapi_csharpPINVOKE.psmove_reset_magnetometer_calibration(PSMove.getCPtr(move));
  }

  public static void psmove_save_magnetometer_calibration(PSMove move) {
    psmoveapi_csharpPINVOKE.psmove_save_magnetometer_calibration(PSMove.getCPtr(move));
  }

  public static float psmove_get_magnetometer_calibration_range(PSMove move) {
    float ret = psmoveapi_csharpPINVOKE.psmove_get_magnetometer_calibration_range(PSMove.getCPtr(move));
    return ret;
  }

  public static PSMove_Bool psmove_has_calibration(PSMove move) {
    PSMove_Bool ret = (PSMove_Bool)psmoveapi_csharpPINVOKE.psmove_has_calibration(PSMove.getCPtr(move));
    return ret;
  }

  public static void psmove_dump_calibration(PSMove move) {
    psmoveapi_csharpPINVOKE.psmove_dump_calibration(PSMove.getCPtr(move));
  }

  public static void psmove_enable_orientation(PSMove move, PSMove_Bool enabled) {
    psmoveapi_csharpPINVOKE.psmove_enable_orientation(PSMove.getCPtr(move), (int)enabled);
  }

  public static PSMove_Bool psmove_has_orientation(PSMove move) {
    PSMove_Bool ret = (PSMove_Bool)psmoveapi_csharpPINVOKE.psmove_has_orientation(PSMove.getCPtr(move));
    return ret;
  }

  public static void psmove_get_orientation(PSMove move, SWIGTYPE_p_float w, SWIGTYPE_p_float x, SWIGTYPE_p_float y, SWIGTYPE_p_float z) {
    psmoveapi_csharpPINVOKE.psmove_get_orientation(PSMove.getCPtr(move), SWIGTYPE_p_float.getCPtr(w), SWIGTYPE_p_float.getCPtr(x), SWIGTYPE_p_float.getCPtr(y), SWIGTYPE_p_float.getCPtr(z));
  }

  public static void psmove_reset_orientation(PSMove move) {
    psmoveapi_csharpPINVOKE.psmove_reset_orientation(PSMove.getCPtr(move));
  }

  public static void psmove_set_orientation_fusion_type(PSMove move, PSMoveOrientation_Fusion_Type fusion_type) {
    psmoveapi_csharpPINVOKE.psmove_set_orientation_fusion_type(PSMove.getCPtr(move), (int)fusion_type);
  }

  public static void psmove_set_calibration_pose(PSMove move, PSMove_CalibrationPose_Type calibration_pose) {
    psmoveapi_csharpPINVOKE.psmove_set_calibration_pose(PSMove.getCPtr(move), (int)calibration_pose);
  }

  public static void psmove_set_calibration_transform(PSMove move, _PSMove_3AxisTransform transform) {
    psmoveapi_csharpPINVOKE.psmove_set_calibration_transform(PSMove.getCPtr(move), _PSMove_3AxisTransform.getCPtr(transform));
  }

  public static void psmove_get_identity_gravity_calibration_direction(PSMove move, _PSMove_3AxisVector out_a) {
    psmoveapi_csharpPINVOKE.psmove_get_identity_gravity_calibration_direction(PSMove.getCPtr(move), _PSMove_3AxisVector.getCPtr(out_a));
  }

  public static void psmove_get_transformed_gravity_calibration_direction(PSMove move, _PSMove_3AxisVector out_a) {
    psmoveapi_csharpPINVOKE.psmove_get_transformed_gravity_calibration_direction(PSMove.getCPtr(move), _PSMove_3AxisVector.getCPtr(out_a));
  }

  public static void psmove_get_identity_magnetometer_calibration_direction(PSMove move, _PSMove_3AxisVector out_m) {
    psmoveapi_csharpPINVOKE.psmove_get_identity_magnetometer_calibration_direction(PSMove.getCPtr(move), _PSMove_3AxisVector.getCPtr(out_m));
  }

  public static void psmove_get_transformed_magnetometer_calibration_direction(PSMove move, _PSMove_3AxisVector out_m) {
    psmoveapi_csharpPINVOKE.psmove_get_transformed_magnetometer_calibration_direction(PSMove.getCPtr(move), _PSMove_3AxisVector.getCPtr(out_m));
  }

  public static void psmove_set_magnetometer_calibration_direction(PSMove move, _PSMove_3AxisVector m) {
    psmoveapi_csharpPINVOKE.psmove_set_magnetometer_calibration_direction(PSMove.getCPtr(move), _PSMove_3AxisVector.getCPtr(m));
  }

  public static void psmove_set_sensor_data_basis(PSMove move, PSMove_SensorDataBasis_Type basis_type) {
    psmoveapi_csharpPINVOKE.psmove_set_sensor_data_basis(PSMove.getCPtr(move), (int)basis_type);
  }

  public static void psmove_set_sensor_data_transform(PSMove move, _PSMove_3AxisTransform transform) {
    psmoveapi_csharpPINVOKE.psmove_set_sensor_data_transform(PSMove.getCPtr(move), _PSMove_3AxisTransform.getCPtr(transform));
  }

  public static void psmove_get_transformed_magnetometer_direction(PSMove move, _PSMove_3AxisVector out_m) {
    psmoveapi_csharpPINVOKE.psmove_get_transformed_magnetometer_direction(PSMove.getCPtr(move), _PSMove_3AxisVector.getCPtr(out_m));
  }

  public static void psmove_get_transformed_accelerometer_frame_3axisvector(PSMove move, Frame frame, _PSMove_3AxisVector out_a) {
    psmoveapi_csharpPINVOKE.psmove_get_transformed_accelerometer_frame_3axisvector(PSMove.getCPtr(move), (int)frame, _PSMove_3AxisVector.getCPtr(out_a));
  }

  public static void psmove_get_transformed_accelerometer_frame_direction(PSMove move, Frame frame, _PSMove_3AxisVector out_a) {
    psmoveapi_csharpPINVOKE.psmove_get_transformed_accelerometer_frame_direction(PSMove.getCPtr(move), (int)frame, _PSMove_3AxisVector.getCPtr(out_a));
  }

  public static void psmove_get_transformed_gyroscope_frame_3axisvector(PSMove move, Frame frame, _PSMove_3AxisVector out_w) {
    psmoveapi_csharpPINVOKE.psmove_get_transformed_gyroscope_frame_3axisvector(PSMove.getCPtr(move), (int)frame, _PSMove_3AxisVector.getCPtr(out_w));
  }

  public static void psmove_disconnect(PSMove move) {
    psmoveapi_csharpPINVOKE.psmove_disconnect(PSMove.getCPtr(move));
  }

  public static void psmove_reinit() {
    psmoveapi_csharpPINVOKE.psmove_reinit();
  }

  public static int psmove_util_get_ticks() {
    int ret = psmoveapi_csharpPINVOKE.psmove_util_get_ticks();
    return ret;
  }

  public static string psmove_util_get_data_dir() {
    string ret = psmoveapi_csharpPINVOKE.psmove_util_get_data_dir();
    return ret;
  }

  public static string psmove_util_get_file_path(string filename) {
    string ret = psmoveapi_csharpPINVOKE.psmove_util_get_file_path(filename);
    return ret;
  }

  public static string psmove_util_get_system_file_path(string filename) {
    string ret = psmoveapi_csharpPINVOKE.psmove_util_get_system_file_path(filename);
    return ret;
  }

  public static int psmove_util_get_env_int(string name) {
    int ret = psmoveapi_csharpPINVOKE.psmove_util_get_env_int(name);
    return ret;
  }

  public static string psmove_util_get_env_string(string name) {
    string ret = psmoveapi_csharpPINVOKE.psmove_util_get_env_string(name);
    return ret;
  }

  public static int init(PSMove_Version version) {
    int ret = psmoveapi_csharpPINVOKE.init((int)version);
    return ret;
  }

  public static void set_remote_config(RemoteConfig config) {
    psmoveapi_csharpPINVOKE.set_remote_config((int)config);
  }

  public static int count_connected() {
    int ret = psmoveapi_csharpPINVOKE.count_connected();
    return ret;
  }

  public static void reinit() {
    psmoveapi_csharpPINVOKE.reinit();
  }

  public static readonly int PSMOVE_EXT_DATA_BUF_SIZE = psmoveapi_csharpPINVOKE.PSMOVE_EXT_DATA_BUF_SIZE_get();
}

}
