/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package io.thp.psmove;

public enum RemoteConfig {
  PSMove_LocalAndRemote(0),
  PSMove_OnlyLocal(1),
  PSMove_OnlyRemote(2);

  public final int swigValue() {
    return swigValue;
  }

  public static RemoteConfig swigToEnum(int swigValue) {
    RemoteConfig[] swigValues = RemoteConfig.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (RemoteConfig swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + RemoteConfig.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private RemoteConfig() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private RemoteConfig(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private RemoteConfig(RemoteConfig swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

